### ISSUE TITLE
Laporan: Penggunaan nama bulan instead of numeric

### ISSUE THREAD

**Issue by jankrix** [triismardiko/lababook-v2#16]
![WhatsApp Image 2020-08-04 at 3 02 45 PM](https://user-images.githubusercontent.com/284005/89269079-9ea5e500-d663-11ea-9255-959948083644.jpeg)
i.e. Mengganti "Bulan 8" menjadi "Agustus"
i.e. mengganti "Minggu 32 2020" menjadi "Agustus Minggu 1 2020"

**Comment by triismardiko** [comment]
"Minggu 32 2020" menjadi "Agustus Minggu 1 2020" still looking for algorithme

**Comment by jankrix** [comment]
![image](https://user-images.githubusercontent.com/284005/89705576-cb6e3b00-d988-11ea-922c-9e2983a7f1c1.png)
 tinggal masalah di styling aja
