### ISSUE TITLE
Edit Akun

### ISSUE THREAD

**Issue by fadirru** [triismardiko/lababook-v2#30]
Alurnya edit salah satu nama buku->save

Lalu saat pindah buku, placeholder nama buku di index tsb akan terisi oleh text yang kita edit sebelumnya.

Tombol back pada appbar edit akun punya autosave, jadi pas user gajadi save dengan keadaan state di atas, maka akan terjadi penamaan buku yang sama

**Comment by fadirru** [comment]
- Tipe usaha buku x mengikuti last edited di buku sebelumnya
- Nama user di card masih narik dari last edited buku sebelumnya
![Screenshot_20200809-101846](https://user-images.githubusercontent.com/58131058/89724168-cf9e6500-da29-11ea-853d-1bf33126a44a.png)
![Screenshot_20200809-101459](https://user-images.githubusercontent.com/58131058/89724174-d6c57300-da29-11ea-9598-947dd0a3d38b.png)
![Screenshot_20200809-101836](https://user-images.githubusercontent.com/58131058/89724175-d88f3680-da29-11ea-816c-2ab3697d9c74.png)

**Comment by jankrix** [comment]
Pas saving, profile picture belum masuk DB

**Comment by fadirru** [comment]
Edit foto profile yang last edited di salah satu buku bakalan implemen ke semua buku
