### ISSUE TITLE
Contact Us: Not working

### ISSUE THREAD

**Issue by jankrix** [triismardiko/lababook-v2#7]
Contact us dari menu more belum jalan

**Comment by triismardiko** [comment]
Untuk ini keputusannya mau kirim form data atau link whatsapp.

**Comment by jankrix** [comment]
whatsapp aja bro

**Comment by triismardiko** [comment]
Whatsapp Contact Centernya boleh di infokan ?

**Comment by jankrix** [comment]
![image](https://user-images.githubusercontent.com/284005/89705382-1f782000-d987-11ea-8661-d9eeb95ef154.png)
sementara ada tambahan image gak keluar, whatsapp menyusul

**Comment by jankrix** [comment]
+62 811-2551-057
